version: "3.8"
services:

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - nwDatalakeHouse
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: nwDatalakeHouse
      MINIO_ROOT_PASSWORD: Strong#Pass#2023
    command: server --console-address ":9001" /data

networks:
  nwDatalakeHouse:
    driver: bridge

volumes:
  minio_storage: {}
